// lib/codegen/hooks.ts
type OpenApiSpec = {
  info?: { title?: string }
  paths?: Record<string, Record<string, {
    summary?: string
    operationId?: string
    requestBody?: object
    responses?: Record<string, object>
  }>>
}

type Endpoint = {
  method: string
  path: string
  summary?: string
  operationId?: string
  hasBody: boolean
  hasPathParams: boolean
}

function toFunctionName(method: string, path: string, operationId?: string): string {
  if (operationId) return operationId
  const parts = path
    .replace(/^\//, "")
    .split("/")
    .map((p) => p.replace(/[{}]/g, "").replace(/-./g, (x) => x[1].toUpperCase()))
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
  return method.toLowerCase() + parts.join("")
}

export function generateHooks(spec: object): string {
  const s = spec as OpenApiSpec
  const endpoints: Endpoint[] = []

  if (s.paths) {
    for (const [path, methods] of Object.entries(s.paths)) {
      for (const [method, details] of Object.entries(methods)) {
        if (!["get", "post", "put", "patch", "delete"].includes(method)) continue
        endpoints.push({
          method,
          path,
          summary: details.summary,
          operationId: details.operationId,
          hasBody: !!details.requestBody,
          hasPathParams: /{(\w+)}/.test(path),
        })
      }
    }
  }

  const lines: string[] = [
    `// Generated by Invokix — do not edit manually`,
    `import { useQuery, useMutation } from "@tanstack/react-query"`,
    ``,
  ]

  for (const ep of endpoints) {
    const name = toFunctionName(ep.method, ep.path, ep.operationId)
    const capitalized = name.charAt(0).toUpperCase() + name.slice(1)
    const pathWithTemplate = ep.path.replace(/{(\w+)}/g, "${params.$1}")
    const cleanPath = ep.path.replace(/{(\w+)}/g, ":$1")

    if (ep.method === "get") {
      lines.push(`export const use${capitalized} = (params?: Record<string, string>) =>`)
      lines.push(`  useQuery({`)
      lines.push(`    queryKey: ["${cleanPath}", params],`)
      lines.push(`    queryFn: async () => {`)
      lines.push(`      const res = await fetch(\`\${process.env.NEXT_PUBLIC_API_URL}${pathWithTemplate}\`)`)
      lines.push(`      if (!res.ok) throw new Error("Failed to fetch ${cleanPath}")`)
      lines.push(`      return res.json()`)
      lines.push(`    },`)
      lines.push(`  })`)
      lines.push(``)
    } else {
      const mutationParam = ep.hasBody
        ? "body: Record<string, unknown>"
        : ep.hasPathParams
        ? "params: Record<string, string>"
        : "_?: unknown"

      lines.push(`export const use${capitalized} = () =>`)
      lines.push(`  useMutation({`)
      lines.push(`    mutationFn: async (${mutationParam}) => {`)
      lines.push(`      const res = await fetch(\`\${process.env.NEXT_PUBLIC_API_URL}${pathWithTemplate}\`, {`)
      lines.push(`        method: "${ep.method.toUpperCase()}",`)
      if (ep.hasBody) {
        lines.push(`        body: JSON.stringify(body),`)
        lines.push(`        headers: { "Content-Type": "application/json" },`)
      }
      lines.push(`      })`)
      lines.push(`      if (!res.ok) throw new Error("Failed to ${ep.method} ${cleanPath}")`)
      lines.push(`      return res.json()`)
      lines.push(`    },`)
      lines.push(`  })`)
      lines.push(``)
    }
  }

  return lines.join("\n")
}

export function generateNativeHooks(spec: object): string {
  const base = generateHooks(spec)
  return base
    .replace(
      "// Generated by Invokix — do not edit manually",
      "// Generated by Invokix — React Native"
    )
    .replace(
      `import { useQuery, useMutation } from "@tanstack/react-query"`,
      `import { useQuery, useMutation } from "@tanstack/react-query"\n// React Native optimized — offline aware`
    )
    .replace(
      /useQuery\({/g,
      `useQuery({\n    networkMode: "always",\n    refetchOnWindowFocus: false,`
    )
}