// lib/codegen/zod.ts
type JsonSchema = {
  type?: string
  properties?: Record<string, JsonSchema>
  items?: JsonSchema
  enum?: string[]
  required?: string[]
  $ref?: string
  format?: string
}

type OpenApiSpec = {
  components?: {
    schemas?: Record<string, JsonSchema>
  }
}

function schemaToZod(schema: JsonSchema, required = true): string {
  if (schema.$ref) {
    const name = schema.$ref.split("/").pop() ?? "unknown"
    return `${name}Schema`
  }

  if (schema.enum) {
    return `z.enum([${schema.enum.map((v) => `"${v}"`).join(", ")}])`
  }

  let zod = ""

  switch (schema.type) {
    case "string":
      zod = schema.format === "email"
        ? "z.string().email()"
        : schema.format === "uuid"
        ? "z.string().uuid()"
        : schema.format === "date-time"
        ? "z.string().datetime()"
        : "z.string()"
      break
    case "number":
    case "integer":
      zod = "z.number()"
      break
    case "boolean":
      zod = "z.boolean()"
      break
    case "array":
      zod = schema.items
        ? `z.array(${schemaToZod(schema.items)})`
        : "z.array(z.unknown())"
      break
    case "object":
      if (schema.properties) {
        const fields = Object.entries(schema.properties).map(([key, val]) => {
          const isRequired = schema.required?.includes(key) ?? false
          const zodVal = schemaToZod(val, isRequired)
          return `  ${key}: ${isRequired ? zodVal : `${zodVal}.optional()`}`
        })
        zod = `z.object({\n${fields.join(",\n")}\n})`
      } else {
        zod = "z.record(z.unknown())"
      }
      break
    default:
      zod = "z.unknown()"
  }

  return required ? zod : `${zod}.optional()`
}

export function generateZodSchemas(spec: object): string {
  const s = spec as OpenApiSpec
  const schemas = s.components?.schemas ?? {}

  if (Object.keys(schemas).length === 0) {
    return `// Generated by Invokix\nimport { z } from "zod"\n\n// No schemas found in spec components`
  }

  const lines: string[] = [
    `// Generated by Invokix — do not edit manually`,
    `import { z } from "zod"`,
    ``,
  ]

  for (const [name, schema] of Object.entries(schemas)) {
    lines.push(`export const ${name}Schema = ${schemaToZod(schema)}`)
    lines.push(`export type ${name} = z.infer<typeof ${name}Schema>`)
    lines.push(``)
  }

  return lines.join("\n")
}